<?php
/**
 * Recolize GmbH
 *
 * @section LICENSE
 * This source file is subject to the GNU General Public License Version 3 (GPLv3).
 *
 * @category Recolize
 * @package Recolize_RecommendationEngine
 * @author Recolize GmbH <service@recolize.com>
 * @copyright 2015 Recolize GmbH (http://www.recolize.com)
 * @license http://opensource.org/licenses/GPL-3.0 GNU General Public License Version 3 (GPLv3).
 */
?>
<?php if (Mage::getStoreConfigFlag('recolize_recommendation_engine/general/enable_extension') === true): ?>
    <?php if (Mage::getSingleton('recolize_recommendation_engine/session')->getIsProductAddedToCart() === true): ?>

    <script type="text/javascript">
        var RecolizeParameters = {};
        RecolizeParameters['itemAction'] = 'add_to_cart';
        RecolizeParameters['clickedItemId'] = '<?php echo Mage::getModel('recolize_recommendation_engine/session')->getProductId(); ?>';
        Recolize.Recommendation.Api.request();
    </script>

    <?php Mage::getSingleton('recolize_recommendation_engine/session')->clear(); ?>
    <?php endif; ?>
<?php endif; ?>