<?php
/**
 * Recolize GmbH
 *
 * @section LICENSE
 * This source file is subject to the GNU General Public License Version 3 (GPLv3).
 *
 * @category Recolize
 * @package Recolize_RecommendationEngine
 * @author Recolize GmbH <service@recolize.com>
 * @copyright 2015 Recolize GmbH (http://www.recolize.com)
 * @license http://opensource.org/licenses/GPL-3.0 GNU General Public License Version 3 (GPLv3).
 */
?>
<?php if (Mage::getStoreConfigFlag('recolize_recommendation_engine/general/enable_extension') === true): ?>
    <?php $currentCategoryName = Mage::registry('current_category')->getName(); ?>

    <script type="text/javascript">
        var RecolizeParameters = {};
        RecolizeParameters['specialPageType'] = 'category';
        RecolizeParameters['categoryId'] = '<?php echo $currentCategoryName ?>';
    </script>
<?php endif; ?>