<?php if (Mage::getStoreConfigFlag('recolize_recommendation_engine/general/enable_extension') === true): ?>
    <?php $currentCategoryId = Mage::registry('current_category')->getId(); ?>

    <div style="display: none">
        <script type="text/javascript">
            var RecolizeParameters = {};
            RecolizeParameters['specialPageType'] = 'category';
            RecolizeParameters['categoryId'] = '<?php echo $currentCategoryId ?>';
        </script>
    </div>
<?php endif; ?>