<?php
/**
 * Recolize GmbH
 *
 * @section LICENSE
 * This source file is subject to the GNU General Public License Version 3 (GPLv3).
 *
 * @category Recolize
 * @package Recolize_RecommendationEngine
 * @author Recolize GmbH <service@recolize.com>
 * @copyright 2015 Recolize GmbH (http://www.recolize.com)
 * @license http://opensource.org/licenses/GPL-3.0 GNU General Public License Version 3 (GPLv3).
 */
/**
 * @var Recolize_RecommendationEngine_Block_Userparameter $this
 */
?>
<script type="text/javascript">
    var RecolizeParameters = RecolizeParameters || {};
    RecolizeParameters['User'] = RecolizeParameters['User'] || {};
<?php if ($this->isCustomerLoggedIn() === true): ?>
    RecolizeParameters['User']['id'] = '<?php echo $this->getCustomerId(); ?>';
<?php endif; ?>
    RecolizeParameters['User']['status'] = '<?php echo $this->getCustomerStatus(); ?>';
    RecolizeParameters['User']['group'] = '<?php echo $this->getCustomerGroup(); ?>';
</script>